import { readFileSync, writeFileSync } from 'fs';

const files = [
  'src/data/socrates.ts',
  'src/data/konfucyus.ts',
  'src/data/jung.ts',
  'src/data/unas.ts',
  'src/data/resmiosmani.ts',
  'src/data/tematikHavuz.ts'
];

// Unique replacements - longer ones first to avoid partial matches
const replacements = [
  // Fiil çekimleri - geniş zaman
  ['istemezsiniz', 'istemezsin'],
  ['istersiniz', 'istersin'],
  ['olursunuz', 'olursun'],
  ['kalırsınız', 'kalırsın'],
  ['edersiniz', 'edersin'],
  ['görürsünüz', 'görürsün'],
  ['yaparsınız', 'yaparsın'],
  ['başlarsınız', 'başlarsın'],
  ['kavuşursunuz', 'kavuşursun'],
  ['ulaşırsınız', 'ulaşırsın'],
  ['yaşarsınız', 'yaşarsın'],
  ['çalışırsınız', 'çalışırsın'],
  ['düşünürsünüz', 'düşünürsün'],
  ['bilirsiniz', 'bilirsin'],
  ['anlarsınız', 'anlarsın'],
  ['bulursunuz', 'bulursun'],
  ['hissedersiniz', 'hissedersin'],
  ['söylersiniz', 'söylersin'],
  // Fiil çekimleri - gereklilik
  ['yapmalısınız', 'yapmalısın'],
  ['olmalısınız', 'olmalısın'],
  ['etmelisiniz', 'etmelisin'],
  ['vermelisiniz', 'vermelisin'],
  ['almalısınız', 'almalısın'],
  ['düşünmelisiniz', 'düşünmelisin'],
  ['bilmelisiniz', 'bilmelisin'],
  ['anlamalısınız', 'anlamalısın'],
  ['görmelisiniz', 'görmelisin'],
  ['duymalısınız', 'duymalısın'],
  ['çalışmalısınız', 'çalışmalısın'],
  ['kullanmalısınız', 'kullanmalısın'],
  // Fiil çekimleri - şimdiki zaman
  ['yapıyorsunuz', 'yapıyorsun'],
  ['oluyorsunuz', 'oluyorsun'],
  ['ediyorsunuz', 'ediyorsun'],
  ['görüyorsunuz', 'görüyorsun'],
  ['biliyorsunuz', 'biliyorsun'],
  ['anlıyorsunuz', 'anlıyorsun'],
  ['düşünüyorsunuz', 'düşünüyorsun'],
  ['istiyorsunuz', 'istiyorsun'],
  ['söylüyorsunuz', 'söylüyorsun'],
  // Fiil çekimleri - gelecek zaman
  ['yapacağınız', 'yapacağın'],
  ['olacağınız', 'olacağın'],
  ['edeceğiniz', 'edeceğin'],
  ['göreceğiniz', 'göreceğin'],
  ['bileceğiniz', 'bileceğin'],
  ['alacağınız', 'alacağın'],
  ['vereceğiniz', 'vereceğin'],
  ['düşüneceğiniz', 'düşüneceğin'],
  ['anlayacağınız', 'anlayacağın'],
  ['söyleyeceğiniz', 'söyleyeceğin'],
  // Fiil çekimleri - geçmiş zaman sıfat-fiil
  ['yaptığınız', 'yaptığın'],
  ['olduğunuz', 'olduğun'],
  ['ettiğiniz', 'ettiğin'],
  ['gördüğünüz', 'gördüğün'],
  ['bildiğiniz', 'bildiğin'],
  ['aldığınız', 'aldığın'],
  ['verdiğiniz', 'verdiğin'],
  ['düşündüğünüz', 'düşündüğün'],
  ['anladığınız', 'anladığın'],
  ['söylediğiniz', 'söylediğin'],
  ['yaşadığınız', 'yaşadığın'],
  ['çalıştığınız', 'çalıştığın'],
  ['hissettiğiniz', 'hissettiğin'],
  ['kullandığınız', 'kullandığın'],
  ['beklediğiniz', 'beklediğin'],
  ['sevdiğiniz', 'sevdiğin'],
  ['kıyasladığınız', 'kıyasladığın'],
  // İsim çekimleri - 2. çoğul iyelik
  ['kıyasınız', 'kıyasın'],
  ['versiyonunuz', 'versiyonun'],
  ['potansiyelinizdir', 'potansiyelindir'],
  ['potansiyelinizi', 'potansiyelini'],
  ['potansiyelinize', 'potansiyeline'],
  ['potansiyeliniz', 'potansiyelin'],
  ['yolculuğunuzdaki', 'yolculuğundaki'],
  ['yolculuğunuzun', 'yolculuğunun'],
  ['yolculuğunuzda', 'yolculuğunda'],
  ['yolculuğunuzu', 'yolculuğunu'],
  ['yolculuğunuz', 'yolculuğun'],
  ['farkındalığınızın', 'farkındalığının'],
  ['farkındalığınızı', 'farkındalığını'],
  ['farkındalığınız', 'farkındalığın'],
  ['bilincinizde', 'bilincinde'],
  ['bilincinizin', 'bilincinin'],
  ['bilincinizi', 'bilincini'],
  ['bilinciniz', 'bilincin'],
  ['benliğinizin', 'benliğinin'],
  ['benliğinize', 'benliğine'],
  ['benliğinizi', 'benliğini'],
  ['benliğiniz', 'benliğin'],
  ['kimliğinizin', 'kimliğinin'],
  ['kimliğinizi', 'kimliğini'],
  ['kimliğiniz', 'kimliğin'],
  ['egonuzun', 'egonun'],
  ['egonuzu', 'egonu'],
  ['egonuz', 'egon'],
  ['gölgenizle', 'gölgenle'],
  ['gölgenizin', 'gölgenin'],
  ['gölgenizi', 'gölgeni'],
  ['gölgeniz', 'gölgen'],
  ['maskelerinizden', 'maskelerinden'],
  ['maskelerinizi', 'maskelerini'],
  ['maskeleriniz', 'maskelerin'],
  ['amacınızın', 'amacının'],
  ['amacınız', 'amacın'],
  ['hedefinize', 'hedefine'],
  ['hedefiniz', 'hedefin'],
  // İsim çekimleri - 2. çoğul iyelik (uzun)
  ['iç dünyanızın', 'iç dünyanın'],
  ['iç dünyanızda', 'iç dünyanda'],
  ['iç dünyanızı', 'iç dünyanı'],
  ['iç dünyanız', 'iç dünyan'],
  ['dünyanızın', 'dünyanın'],
  ['dünyanızda', 'dünyanda'],
  ['dünyanızı', 'dünyanı'],
  ['dünyanız', 'dünyan'],
  ['hayatınızın', 'hayatının'],
  ['hayatınızda', 'hayatında'],
  ['hayatınızı', 'hayatını'],
  ['hayatınıza', 'hayatına'],
  ['hayatınız', 'hayatın'],
  ['zihninizin', 'zihninin'],
  ['zihninizde', 'zihninde'],
  ['zihninizi', 'zihnini'],
  ['zihniniz', 'zihnin'],
  ['ruhunuzun', 'ruhunun'],
  ['ruhunuzda', 'ruhunda'],
  ['ruhunuzu', 'ruhunu'],
  ['ruhunuz', 'ruhun'],
  ['bilinçaltınızın', 'bilinçaltının'],
  ['bilinçaltınızı', 'bilinçaltını'],
  ['bilinçaltınız', 'bilinçaltın'],
  // İsim çekimleri - 2. çoğul iyelik (çoğul ekli)
  ['kararlarınızda', 'kararlarında'],
  ['kararlarınızı', 'kararlarını'],
  ['kararlarınız', 'kararların'],
  ['ilişkilerinizde', 'ilişkilerinde'],
  ['ilişkilerinizi', 'ilişkilerini'],
  ['ilişkileriniz', 'ilişkilerin'],
  ['duygularınızda', 'duygularında'],
  ['duygularınızı', 'duygularını'],
  ['duygularınız', 'duyguların'],
  ['korkularınızda', 'korkularında'],
  ['korkularınızı', 'korkularını'],
  ['korkularınız', 'korkuların'],
  ['arzularınızı', 'arzularını'],
  ['arzularınız', 'arzuların'],
  ['sınırlarınızın', 'sınırlarının'],
  ['sınırlarınızı', 'sınırlarını'],
  ['sınırlarınız', 'sınırların'],
  ['yönlerinizle', 'yönlerinle'],
  ['yönlerinizi', 'yönlerini'],
  ['yönleriniz', 'yönlerin'],
  ['parçalarınızın', 'parçalarının'],
  ['parçalarınızla', 'parçalarınla'],
  ['parçalarınız', 'parçaların'],
  ['kusurlarınızla', 'kusurlarınla'],
  ['kusurlarınız', 'kusurların'],
  ['eksikliklerinizle', 'eksikliklerinle'],
  ['eksiklikleriniz', 'eksikliklerin'],
  ['zayıflıklarınızı', 'zayıflıklarını'],
  ['zayıflıklarınız', 'zayıflıkların'],
  ['taraflarınızı', 'taraflarını'],
  ['taraflarınız', 'tarafların'],
  ['değerlerinizle', 'değerlerinle'],
  ['değerlerinizi', 'değerlerini'],
  ['değerleriniz', 'değerlerin'],
  ['yeteneklerinizi', 'yeteneklerini'],
  ['yetenekleriniz', 'yeteneklerin'],
  // Zamirler ve edatlar
  ['kendinizle', 'kendinle'],
  ['kendinizden', 'kendinden'],
  ['kendinize', 'kendine'],
  ['kendinizi', 'kendini'],
  ['kendinizin', 'kendinin'],
  ['kendinizde', 'kendinde'],
  ['kendinizdeki', 'kendindeki'],
  ['kendinizmiş', 'kendinmiş'],
  ['kendinizsiniz', 'kendinsin'],
  ['kendinizdir', 'kendindir'],
  ['kendinizce', 'kendince'],
  ['kendiniz', 'kendin'],
  ['içinizdeki', 'içindeki'],
  ['içinizde', 'içinde'],
  ['içinizden', 'içinden'],
  ['içinize', 'içine'],
  ['içinizi', 'içini'],
  ['içiniz', 'için'],
  // Emir kipleri
  ['yapın', 'yap'],
  ['olun', 'ol'],
  ['gidin', 'git'],
  ['bakın', 'bak'],
  ['düşünün', 'düşün'],
  ['verin', 'ver'],
  ['alın', 'al'],
  ['geliştirin', 'geliştir'],
  ['öğrenin', 'öğren'],
  ['anlayın', 'anla'],
  ['kavrayın', 'kavra'],
  ['deneyin', 'dene'],
  // İsim-fiil ekleri
  ['atmanız', 'atman'],
  ['etmeniz', 'etmen'],
  ['olmanız', 'olman'],
  ['yapmanız', 'yapman'],
  ['görmeniz', 'görmen'],
  ['duymanız', 'duyman'],
  ['bilmeniz', 'bilmen'],
  ['söylemeniz', 'söylemen'],
  // Zamirler
  ['size', 'sana'],
  ['sizin', 'senin'],
  ['sizler', 'sen'],
];

let totalChanges = 0;

for (const filePath of files) {
  let content = readFileSync(filePath, 'utf-8');
  let fileChanges = 0;
  
  for (const [search, replace] of replacements) {
    // Use regex with word boundary to match whole words only
    const regex = new RegExp(search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
    const newContent = content.replace(regex, replace);
    if (newContent !== content) {
      const diff = (content.match(regex) || []).length;
      fileChanges += diff;
      content = newContent;
    }
  }
  
  if (fileChanges > 0) {
    writeFileSync(filePath, content, 'utf-8');
    console.log(`${filePath}: ${fileChanges} değişiklik yapıldı`);
    totalChanges += fileChanges;
  } else {
    console.log(`${filePath}: değişiklik yok`);
  }
}

console.log(`\nToplam: ${totalChanges} değişiklik yapıldı`);
