// generateLocalMessage fonksiyonunu test et
function seededRandom(s) {
  let h = Math.abs(s) | 0;
  h = ((h ^ 0x9e3779b9) + (h << 6) + (h >> 2)) | 0;
  h = ((h ^ 0x85ebca6b) + (h << 3) + (h >> 5)) | 0;
  h = ((h ^ 0xc2b2ae35) + (h << 7) + (h >> 4)) | 0;
  let state = Math.abs(h) % 2147483647;
  if (state <= 0) state = 1;
  return () => {
    state = (state * 16807) % 2147483647;
    return (state - 1) / 2147483646;
  };
}

// Kategoriler
const sosyalKategori = [
  { eylem: 'mesaj at', hedefler: ['bir arkadaşına', 'ailenden birine', 'özlediğine', 'teşekkür etmek istediğine', 'uzun zamandır görmediğin birine', 'bugün aklına gelen ilk kişiye', 'küs olduğun birine', 'birlikte güldüğün birine'], gerekceler: ['kopmuş bir bağı geri getirebilir', 'bir cümle bir ömür hatırlanır', 'iyi ki var dediğin anları çoğaltır', 'basit bir cümle bazen her şeyi değiştirir', 'söylemediğin her şey seni yalnızlaştırır', 'bir selam bin selamı doğurur'] },
  { eylem: 'ara', hedefler: ['bir arkadaşını', 'ailenden birini', 'özlediğin birini', 'merak ettiğin birini', 'sesini duymak istediğin birini', 'yaşlı bir tanıdığını', 'çocukluk arkadaşını', 'bir komşunu'], gerekceler: ['bir ses duymak bazen bin kelimeden iyidir', 'özlediğini söylemek için bugün doğru gün', 'kısa bir arama uzun bir sessizliği bitirebilir', 'merak ettiğini belli etmek bağları güçlendirir', 'telefon iki yönlü bir köprüdür', 'bir selam bir ömre bedeldir'] },
  { eylem: 'teşekkür et', hedefler: ['bir arkadaşına', 'ailenden birine', 'sana iyilik yapmış olana', 'minnettar olduğuna', 'yanında olana', 'sabredene', 'sana inanana', 'farkında olmadığın bir iyilik yapana'], gerekceler: ['minnettarlık karşındakini olduğu kadar seni de iyileştirir', 'bir teşekkür iki gönlü birleştirir', 'küçük bir hareket büyük dalga başlatır', 'iyi ki var dediğin anları çoğaltır', 'şükretmek bereketi artırır', 'bir teşekkür bir ömre bedeldir'] },
  { eylem: 'özür dile', hedefler: ['kırdığın birinden', 'küstüğün birinden', 'sessiz kaldığın birinden', 'affetmek istediğin birinden', 'senden uzaklaşmış olandan', 'kendinden', 'ihmal ettiğin birinden'], gerekceler: ['affetmek karşıdaki için değil kendin içindir', 'söylemediğin pişmanlık söylediğinden daha ağır basar', 'bir adım geri atmak iki adım ileri için fırsattır', 'durmak da bir eylemdir', 'özür dilersen yalnızca sen değil karşındaki de iyileşir'] },
  { eylem: 'söyle', hedefler: ['bir arkadaşına', 'ailenden birine', 'sevdiğine', 'içinden geçeni', 'uzun zamandır söyleyemediğini', 'bir sırrını', 'bir itirafını', 'bir hayalini'], gerekceler: ['söylemekten korktuğun şey tam da söylenmesi gereken şeydir', 'doğru kelime yanlış zamanda bile iyileştirir', 'bir soru bir duvarı yıkabilir', 'içinden gelen ses genellikle doğru olanı söyler', 'sözcüklerin gücünü hafife alma', 'içinde biriken her şey dışarı çıkmayı bekler'] },
  { eylem: 'sor', hedefler: ['merak ettiğin bir şeyi', 'bir arkadaşına', 'kendine', 'bilmediğin bir şeyi', 'içini kemiren soruyu', 'bir bilgeye', 'bir çocuğa', 'bir yabancıya'], gerekceler: ['bir soru bir duvarı yıkabilir', 'bilmediğini kabul etmek öğrenmenin ilk adımıdır', 'merak ettiğin şey seni büyütür', 'soruların cevabı sorunun kendi içindeki sessizlikte gizlidir', 'sormaktan korkma cevap seni bekliyor olabilir'] },
  { eylem: 'gönder', hedefler: ['bir arkadaşına', 'ailenden birine', 'bir notu', 'bir fotoğrafı', 'bir hatırayı', 'bir tebriki', 'bir şiiri'], gerekceler: ['küçük bir hareket büyük dalga başlatır', 'bir cümle bir ömür hatırlanır', 'paylaşmak çoğaltır', 'hatırladıkların şekillendirir', 'bir not bir günü güzelleştirebilir'] },
  { eylem: 'paylaş', hedefler: ['bir arkadaşınla', 'ailenle', 'bir anını', 'bir düşünceyi', 'bir duyguyu', 'bir başarını', 'bir korkunu'], gerekceler: ['mutluluk paylaşıldıkça çoğalır', 'üzüntü paylaşıldıkça azalır', 'paylaşmak çoğaltır', 'iyi ki var dediğin anları çoğaltır', 'paylaştığın her şey seni biraz daha özgürleştirir'] },
  { eylem: 'kucakla', hedefler: ['bir dostunu', 'ailenden birini', 'sevdiğini', 'sarılmayı özlediğin birini', 'kendini', 'bir çocuğu'], gerekceler: ['bir kucaklama bin kelimeden daha fazlasını anlatır', 'sarılmak iyileştirir', 'fiziksel temas ruhu besler', 'kucaklamak ait olmanın en eski dilidir'] },
  { eylem: 'dinle', hedefler: ['bir arkadaşını', 'bir hikayeyi', 'bir şikayeti', 'bir sevinci', 'susmayı tercih eden birini'], gerekceler: ['dinlemek anlamanın ilk adımıdır', 'bazen en büyük iyilik susup dinlemektir', 'herkesin anlatacak bir hikayesi vardır', 'dinlediğini hissettirmek en büyük hediyedir'] },
];

const zihinselKategori = [
  { eylem: 'düşün', hedefler: ['bir kararı', 'bir anıyı', 'bir hayali', 'bir soruyu', 'bugünü', 'bir ihtimali', 'bir ilişkiyi', 'bir sözü'], gerekceler: ['düşünmek hareketsizliğin en aktif halidir', 'kendine sorduğun her soru seni biraz daha özgürleştirir', 'boşluk beyninin sıfırlanma anıdır', 'içgörü sessizlikte filizlenir', 'derin düşünce berrak bir göl gibidir'] },
  { eylem: 'hatırla', hedefler: ['güzel bir anıyı', 'bir dersi', 'bir yüzü', 'bir duyguyu', 'nereden geldiğini', 'bir gülüşü', 'bir vedayı', 'bir başlangıcı'], gerekceler: ['hatırladıkların şekillendirir', 'geçmişte kalan bazı versiyonların hâlâ içinde yaşar', 'unutmak da bir tür özgürlüktür', 'anılar geleceğin tohumlarıdır', 'hatırlamak iyileşmenin ilk adımıdır'] },
  { eylem: 'unut', hedefler: ['bir kırgınlığı', 'bir hatayı', 'geçmişte kalmış bir anı', 'seni yoran bir düşünceyi', 'affettiğin bir şeyi', 'bir başarısızlığı', 'bir pişmanlığı'], gerekceler: ['unutmak da bir tür özgürlüktür', 'unuttuğun şeyler seni yormaz', 'hafiflemek de bir eylemdir', 'affetmek karşıdaki için değil kendin içindir', 'unutmak yeniye yer açmaktır'] },
  { eylem: 'affet', hedefler: ['kendini', 'kırdığın birini', 'seni kıranı', 'geçmişte takılı kaldığın bir anı', 'içindeki çocuğu', 'bir hayal kırıklığını', 'beklentilerini'], gerekceler: ['affetmek karşıdaki için değil kendin içindir', 'hafiflemek de bir eylemdir', 'geçmişte kalan bazı versiyonların hâlâ içinde yaşar', 'karanlık taraflarını kabul eden bütünlüğe bir adım yaklaşır', 'affetmek özgürleşmektir'] },
  { eylem: 'karar ver', hedefler: ['bir konuda', 'bir seçim yapmaya', 'bir yön belirlemeye', 'bir şeyi bitirmeye', 'bir şeye başlamaya', 'bir değişime', 'bir adıma'], gerekceler: ['karar vermek harekete geçmenin ilk adımıdır', 'seçim yapmamak da bir seçimdir', 'her bitiş gizli bir başlangıcın habercisidir', 'başlamak bitirmenin yarısıdır', 'kararsızlık kararın kendisinden daha yorucudur'] },
  { eylem: 'kabul et', hedefler: ['bir gerçeği', 'bir duyguyu', 'bir durumu', 'kendini', 'değiştiremeyeceğin bir şeyi', 'bir belirsizliği', 'bir kaybı'], gerekceler: ['kabul etmek direnmeyi bırakmaktır', 'kendi zayıflığını kabul etmek en büyük cesarettir', 'karanlık taraflarını kabul eden bütünlüğe bir adım yaklaşır', 'durmak da bir eylemdir', 'kabul teslimiyet değil olgunluktur'] },
  { eylem: 'reddet', hedefler: ['seni tüketen bir alışkanlığı', 'hayır demen gereken bir şeyi', 'bir beklentiyi', 'zoraki bir kabullenişi', 'içine sinmeyen bir teklifi', 'bir baskıyı', 'bir rolü'], gerekceler: ['hayır demek kendine evet demenin tek yoludur', 'seni tüketen şey evet demek zorunda hissetmendir', 'kesmek devam etmekten bazen daha iyidir', 'vazgeçmek bazen kazanmaktır', 'sınır koymak sevgidir'] },
  { eylem: 'seç', hedefler: ['bir yönü', 'bir yolu', 'bir duruşu', 'kendini', 'seni mutlu edecek olanı', 'zor olanı', 'doğru olanı'], gerekceler: ['seçim yapmamak da bir seçimdir', 'her bitiş gizli bir başlangıcın habercisidir', 'karar vermek harekete geçmenin ilk adımıdır', 'başlamak bitirmenin yarısıdır', 'seçimlerin seni sen yapar'] },
  { eylem: 'bekle', hedefler: ['doğru zamanı', 'bir cevabı', 'sabretmeyi', 'bir işaret', 'içindeki sesi', 'bir mevsimi', 'bir dönüşü'], gerekceler: ['beklemek de harekete geçmek kadar güçlüdür', 'sabır acıyı tatlandırır', 'boşluk beyninin sıfırlanma anıdır', 'zaman insanın olgunlaşması için gereken bir araçtır', 'her şeyin bir zamanı vardır'] },
  { eylem: 'vazgeç', hedefler: ['seni yoran bir uğraştan', 'bir inadından', 'bir alışkanlığından', 'bir takıntından', 'kontrol etmeye çalıştığın bir şeyden', 'bir savaştan', 'bir kıyaslamadan'], gerekceler: ['vazgeçmek kaybetmek değil yön değiştirmektir', 'vazgeçmek bazen kazanmaktır', 'kesmek devam etmekten bazen daha iyidir', 'hafiflemek de bir eylemdir', 'bırakmak kazanmaktır'] },
  { eylem: 'dene', hedefler: ['yeni bir şeyi', 'farklı bir yaklaşımı', 'cesaret ettiğin bir şeyi', 'ertelediğin bir şeyi', 'korktuğun bir şeyi', 'bilmediğin bir şeyi', 'bir kez daha'], gerekceler: ['cesaret korkuyu hissetmek ve yine de yürümektir', 'başlamak bitirmenin yarısıdır', 'yanılmak doğruyu bulmanın tek yoludur', 'düşmek kalkmayı öğretir', 'denememek pişmanlığın en büyüğüdür'] },
  { eylem: 'sorgula', hedefler: ['bir inancını', 'bir alışkanlığını', 'bir korkunu', 'bir ön yargını', 'neden diye', 'bir kalıbı', 'bir varsayımı'], gerekceler: ['sorgulamak büyümenin motorudur', 'bildiğini sanmak öğrenmenin önündeki en büyük engeldir', 'bir soru bir duvarı yıkabilir', 'derin sorular derin cevaplar getirir'] },
];

const fizikselKategori = [
  { eylem: 'yürü', hedefler: ['bir süre', 'biraz', 'dışarıda', 'düşüncelerinle', 'hiçbir yere varmadan', 'bir parkta', 'yağmurda', 'sabah erken', 'gece geç saatte'], gerekceler: ['koşmak zorunda değilsin yürümek de varmak demektir', 'bir adım geri atmak iki adım ileri için fırsattır', 'hareket etmek zihni açar', 'dışarıdaki her şey bir süre sonra seninle ilgili olmaktan çıkar', 'yürümek düşünceleri berraklaştırır', 'her adım yeni bir başlangıçtır'] },
  { eylem: 'nefes al', hedefler: ['derin derin', 'birkaç kere', 'yavaşça', 'farkındalıkla', 'sakinleşene kadar', 'burnundan', 'karnından', 'sayarak'], gerekceler: ['nefes almak yaşadığının kanıtıdır', 'derin nefes almak yaşamak istediğinin kanıtıdır', 'boşluk beyninin sıfırlanma anıdır', 'durmak da bir eylemdir', 'nefesin farkında olmak anın farkında olmaktır', 'bir nefes her şeyi değiştirebilir'] },
  { eylem: 'otur', hedefler: ['sessizce', 'bir süre', 'kendinle', 'düşüncelerinle', 'hiçbir şey yapmadan', 'bir bankta', 'güneşte', 'gölgede'], gerekceler: ['durmak da bir eylemdir', 'boşluk beyninin sıfırlanma anıdır', 'sessizlik bir boşluk değil bir cevaptır', 'içgörü sessizlikte filizlenir', 'oturmak direnmeyi bırakmaktır', 'bazen en verimli iş hiçbir şey yapmamaktır'] },
  { eylem: 'kalk', hedefler: ['ve bir şey yap', 've hareket et', 've başla', 've devam et', 've dene', 've dans et', 've esne', 've koş'], gerekceler: ['başlamak bitirmenin yarısıdır', 'hareket etmek zihni açar', 'kalkmak düşmüş olmayı unutturur', 'devam etmek bitirmiş olmaktır', 'bir hareket bin düşünceyi değiştirir', 'bedenin hareketi ruhu da peşinden sürükler'] },
  { eylem: 'gülümse', hedefler: ['kendine', 'bir yabancıya', 'bugüne', 'hayata', 'içindeki çocuğa', 'aynadaki yansımana', 'bir anıya', 'bir fotoğrafa'], gerekceler: ['bir gülümseme savaşı bitirebilir', 'küçük bir hareket büyük dalga başlatır', 'gülümsemek en basit iyilik hareketidir', 'içimizdeki çocuk en saf bakış açısıdır', 'gülümsemek beyni yeniden programlar', 'bir gülümseme bir ömre bedeldir'] },
  { eylem: 'dur', hedefler: ['bir an', 've etrafına bak', 've dinle', 've fark et', 've nefes al', 've hisset', 've şükret', 've gülümse'], gerekceler: ['durmak da bir eylemdir', 'bir an durup bakmak en büyük keşiftir', 'hız fark etmeyi engeller', 'boşluk beyninin sıfırlanma anıdır', 'durmak kaybolmak değil yön bulmaktır', 'en büyük içgörüler duraklamalarda doğar'] },
  { eylem: 'bak', hedefler: ['etrafına', 'gökyüzüne', 'bir an', 'derinlemesine', 'fark etmediklerine', 'bir çiçeğe', 'bir yaprağa', 'bir yüze', 'bir manzaraya'], gerekceler: ['bir an durup bakmak en büyük keşiftir', 'gökyüzü senin aynandır', 'hız fark etmeyi engeller', 'küçük şeylerdeki büyük resmi görmek olgunluktur', 'bakmak görmek için yeterli değildir fark etmek gerekir', 'her şeyin güzelliği onu nasıl gördüğünde saklıdır'] },
  { eylem: 'dinle', hedefler: ['bir şarkıyı', 'sessizliği', 'bir dostu', 'iç sesini', 'doğanın sesini', 'bir kuşu', 'rüzgarı', 'bir enstrümanı'], gerekceler: ['sessizlikte konuşan ses en gerçek sestir', 'dışarıdaki gürültü dinince içerideki netleşir', 'dinlemek anlamanın ilk adımıdır', 'sessizlik bir boşluk değil bir cevaptır', 'doğanın sesi ruhu onarır', 'her sesin bir frekansı ve her frekansın bir anlamı vardır'] },
  { eylem: 'yaz', hedefler: ['bir mektup', 'bir şiir', 'bir günlük', 'içinden geçenleri', 'bir teşekkür notu', 'bir hayalini', 'bir korkunu', 'bir hedefini', 'bir soruyu'], gerekceler: ['bir cümle bir ömür hatırlanır', 'yazmak düşünceleri netleştirir', 'söylemediğin her şey seni yalnızlaştırır', 'basit bir cümle bazen her şeyi değiştirir', 'yazmak içini dökmekten daha fazlasıdır kendini inşa etmektir', 'kağıda dökülen her şey biraz daha hafifler'] },
  { eylem: 'sil', hedefler: ['bir fotoğrafı', 'bir mesajı', 'bir numarayı', 'bir hatırayı', 'geçmişin izlerini', 'bir uygulamayı', 'bir dosyayı', 'bir alışkanlığı'], gerekceler: ['silmek taşımaktan daha cesurcadır', 'hafiflemek de bir eylemdir', 'eskiyi bitirmeden yeniye yer açılamaz', 'unutmak da bir tür özgürlüktür', 'silmek yok etmek değil yer açmaktır', 'dijital minimalizm zihinsel berraklık getirir'] },
  { eylem: 'esne', hedefler: ['sabah uyanınca', 'birkaç dakika', 'boynunu', 'sırtını', 'bacaklarını', 'tüm bedenini'], gerekceler: ['esnemek bedeni uyandırır', 'hareket etmek zihni açar', 'bedenin esnekliği ruhun esnekliğini yansıtır', 'küçük bir esneme büyük bir rahatlama sağlar'] },
  { eylem: 'koş', hedefler: ['kısa bir mesafe', 'bir parkta', 'sabah erken', 'akşamüstü', 'müzikle', 'hiçbir yere yetişmeden'], gerekceler: ['koşmak özgürlüğün en saf halidir', 'hareket etmek zihni açar', 'koşarken düşünceler de akar', 'her adım bir öncekinden daha güçlüdür'] },
  { eylem: 'dans et', hedefler: ['bir şarkıyla', 'mutfakta', 'sabah ilk iş', 'kimse yokken', 'müziğin ritmine', 'içinden geldiği gibi'], gerekceler: ['dans etmek ruhun bedende özgürleşmesidir', 'müzik ruhu besler dans etmek onu özgür bırakır', 'dans etmek için iyi bir sebep gerekmez', 'bedenin ritmi ruhun ritmidir'] },
];

const donusumKategori = [
  { eylem: 'değiştir', hedefler: ['bir alışkanlığını', 'bir bakış açını', 'bir rutinini', 'küçük bir şeyi', 'başlamak istediğin bir şeyi', 'bir düşünce kalıbını', 'bir tepkini', 'bir önceliğini'], gerekceler: ['değişmek zorundasın çünkü her şey değişiyor', 'farkına vardığın alışkanlıkları değiştirebilirsin', 'değişimden korkmak hayattan korkmaktır', 'dönüşüm sancılı ama kaçınılmaz bir süreçtir', 'değişim kaçınılmazdır acı ise seçimdir', 'küçük bir değişiklik büyük bir fark yaratabilir'] },
  { eylem: 'başla', hedefler: ['küçük bir adımla', 'ertelediğin bir şeye', 'yeni bir alışkanlığa', 'bir günlük tutmaya', 'bir projeye', 'bir kitaba', 'bir kursa', 'bir yolculuğa', 'bir mektuba'], gerekceler: ['başlamak bitirmenin yarısıdır', 'her başlangıç bir önceki bitişi gerektirir', 'küçük bir hareket büyük dalga başlatır', 'her bitiş gizli bir başlangıcın habercisidir', 'başlamak için mükemmel anı beklemek en büyük hatadır', 'bir adım atmak yolun yarısıdır'] },
  { eylem: 'devam et', hedefler: ['yoluna', 'bildiğin gibi', 'vazgeçmeden', 'bir gün daha', 'yavaş da olsa', 'aksamalara rağmen', 'inancınla', 'sabırla'], gerekceler: ['devam etmek bitirmiş olmaktır', 'koşmak zorunda değilsin yürümek de varmak demektir', 'insan bir nehir gibi kendi yolunu eninde sonunda bulur', 'yolunu kucaklayan fırtınanın ortasında bile huzuru bulur', 'devam etmek direnmektir ve direnmek var olmaktır', 'her gün bir önceki günden daha güçlüsün'] },
  { eylem: 'bırak', hedefler: ['kontrol etmeyi', 'endişelenmeyi', 'bir yükü', 'geçmişi', 'olması gerektiği gibi olmayanı', 'bir beklentiyi', 'bir kıyası', 'bir alışkanlığı'], gerekceler: ['vazgeçmek kaybetmek değil yön değiştirmektir', 'hafiflemek de bir eylemdir', 'esnek ol ki fırtınalarda kırılmayasın', 'direndiğin şey varlığını sürdürmeye devam eder', 'bırakmak özgürleşmenin ilk adımıdır', 'bazen en güçlü hareket bırakmaktır'] },
  { eylem: 'dönüş', hedefler: ['kendine', 'özüne', 'bir başlangıca', 'bir eskiye', 'bir yuvaya', 'bir kökene', 'bir ilk sevgiye', 'bir çocukluk anısına'], gerekceler: ['kendi küllerinden doğmak her insanın doğasında vardır', 'insan her krizde eski derisini atıp yenilenir', 'her bitiş gizli bir başlangıcın habercisidir', 'dönüşüm sancılı ama kaçınılmaz bir süreçtir', 'dönüş bir geri adım değil derinleşmedir', 'bazen ilerlemek için geriye gitmek gerekir'] },
  { eylem: 'yenilen', hedefler: ['bir rutini terk ederek', 'yeni bir bakış açısıyla', 'eski kalıpları kırarak', 'kendini yeniden keşfederek', 'bir sabah uyanıp farklı bir insan olarak'], gerekceler: ['her gün yeniden doğma şansın var', 'dönüşüm sancılı ama kaçınılmaz bir süreçtir', 'insan her krizde eski derisini atıp yenilenir', 'yenilenmek için önce eskiyi bırakmak gerekir'] },
  { eylem: 'büyü', hedefler: ['bir zorluğun içinden', 'bir hatadan', 'bir kayıptan', 'bir sessizlikten', 'bir yalnızlıktan', 'bir sevgiden'], gerekceler: ['büyümek acıyı da kucaklamaktır', 'her zorluk içinde bir ders taşır', 'en karanlık geceler en parlak yıldızları doğurur', 'büyümek bir tercihtir herkes yaşlanır ama herkes büyümez'] },
  { eylem: 'dönüştür', hedefler: ['bir acıyı', 'bir korkuyu', 'bir engeli', 'bir hatayı', 'bir kaybı', 'bir öfkeyi'], gerekceler: ['her şey dönüşebilir yeter ki izin ver', 'acı öğretir korku büyütür engel güçlendirir', 'dönüşüm sancılı ama kaçınılmaz bir süreçtir', 'bir şeyi dönüştürmek onu olduğu gibi kabul etmekle başlar'] },
];

const bakimKategori = [
  { eylem: 'temizle', hedefler: ['bir odayı', 'masanı', 'zihnini', 'bir alanı', 'dağınıklığı', 'bir dolabı', 'bir çekmeceyi', 'telefonunun hafızasını'], gerekceler: ['temizlik zihni de temizler', 'düzen dışarıdan içeriye doğru işler', 'boşluk beyninin sıfırlanma anıdır', 'küçük bir hareket büyük dalga başlatır', 'temiz bir alan temiz bir zihin demektir', 'dağınıklığı gidermek içsel bir ferahlama sağlar'] },
  { eylem: 'düzenle', hedefler: ['bir alanı', 'bir listeyi', 'önceliklerini', 'bir dolabı', 'dağınık düşüncelerini', 'bir takvimi', 'bir dosyayı', 'bir koleksiyonu'], gerekceler: ['düzen dışarıdan içeriye doğru işler', 'temizlik zihni de temizler', 'plan yapmak geleceği şimdiden yaşamaktır', 'küç